name: example
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  async_forms:
    path: ../../async_forms

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.0
  freezed_annotation: ^2.1.0
  decimal: ^2.2.0
  regexpattern: ^2.0.1
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true
